server:
  port: 7788
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/test
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.springboot.domain
